http:
  port: "8081"

enc:
  key: "a7d7j2jg20aj27ja"
  
database:
  uhub:
    host: "mysql-98046-0.cloudclusters.net"
    port: "19059"
    user: "admin"
    password: "![O6+HV4Tpmhcr4k8OSd39fg==]"
    database: "realtimeproject"